required = [
  "github.com/golang/dep/cmd/dep"
]

[[constraint]]
  branch = "master"
  name = "github.com/bazelbuild/buildtools"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  branch = "master"
  name = "golang.org/x/build"

[[constraint]]
  name = "github.com/golang/dep"
  version = "v0.4.1"

[prune]
  unused-packages = true
  go-tests = true
  non-go = true
